CREATE TABLE BOOK_METADATA_CACHE (
    BOOK_ID varchar NOT NULL PRIMARY KEY,
    COMICINFO_BLOB blob NULL,
    EPUB_PACKAGE_BLOB blob NULL,
    COMICINFO_HASH char(64) NULL,
    EPUB_PACKAGE_HASH char(64) NULL,
    LAST_MODIFIED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID) ON DELETE CASCADE
);
