version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "deps(ci)"
    #      include: "scope"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/komga-rust"
    commit-message:
      prefix: "deps(rust)"
    schedule:
      interval: "weekly"
