from __future__ import annotations


ROUTES: dict[str, dict[str, object]] = {
    'browse-readlist': {
        'route': 'browse-readlist',
        'path': '/readlists/readlist-2',
        'selector': '[data-testid="item-browser-root"]',
        'panelSelector': '[data-testid="item-browser-root"]',
        'panelKey': 'itemBrowserFound',
        'panelExpected': True,
        'siblingNavigationSelector': '[data-testid="browse-book-sibling-navigation"]',
        'siblingNavigationExpected': False,
        'sourceFile': 'komga-webui/src/views/BrowseReadList.vue',
        'sourceFiles': [
            'komga-webui/src/views/BrowseReadList.vue',
            'komga-webui/src/components/ItemBrowser.vue',
            'komga-webui/src/components/ItemCard.vue',
            'komga-webui/src/types/items.ts',
            'komga-webui/src/types/context.ts',
        ],
        'scenarioSourceFiles': [
            'komga-webui/src/views/BrowseReadList.vue',
            'komga-webui/src/views/BrowseBook.vue',
            'komga-webui/src/components/ItemBrowser.vue',
            'komga-webui/src/components/ItemCard.vue',
            'komga-webui/src/types/items.ts',
            'komga-webui/src/types/context.ts',
        ],
        'sourceMetadataFragments': [
            'readList.name',
            'readList.summary',
            'origin: ContextOrigin.READLIST, id: readListId',
            "query: {context: this.item?.context?.origin, contextId: this.item?.context?.id}",
        ],
        'metadataFragments': ['ReadList 2', 'Download'],
        'metadataMinimumMatches': 2,
        'ownedRequests': [],
        'scenario': {
            'type': 'readlist-origin-entry',
            'contextOrigin': 'READLIST',
            'contextId': 'readlist-2',
            'readListName': 'ReadList 2',
            'entryBookId': 'book-1',
            'entryBookPath': '/book/book-1?context=READLIST&contextId=readlist-2',
        },
    },
    'browse-series': {
        'route': 'browse-series',
        'path': '/series/series-1',
        'selector': '[data-testid="browse-series-root"]',
        'panelSelector': '[data-testid="browse-series-collections-panel"]',
        'panelKey': 'collectionsPanelFound',
        'panelExpected': True,
        'siblingNavigationSelector': '[data-testid="browse-book-sibling-navigation"]',
        'siblingNavigationExpected': False,
        'sourceFile': 'komga-webui/src/views/BrowseSeries.vue',
        'sourceMetadataFragments': ['series.metadata.title', 'series.metadata.summary', 'authorsByRole'],
        'metadataFragments': ['series', 'featured', 'fantasy', 'alice'],
        'metadataMinimumMatches': 2,
        'ownedRequests': [
            {
                'label': 'series-detail',
                'method': 'GET',
                'urlEndsWith': '/api/v1/series/series-1',
                'requestPath': '/api/v1/series/series-1',
            },
            {
                'label': 'series-collections',
                'method': 'GET',
                'urlEndsWith': '/api/v1/series/series-1/collections',
                'requestPath': '/api/v1/series/series-1/collections',
            },
            {
                'label': 'series-books-list',
                'method': 'POST',
                'urlContains': '/api/v1/books/list?page=0&size=20&sort=metadata.numberSort',
                'postDataIncludes': ['AllOfBook', 'SeriesId', 'series-1'],
                'requestPath': '/api/v1/books/list?page=0&size=20&sort=metadata.numberSort,asc',
                'body': '{"condition":{"type":"AllOfBook","conditions":[{"type":"SeriesId","operator":"is","value":"series-1"}]}}',
            },
        ],
    },
    'browse-book': {
        'route': 'browse-book',
        'path': '/book/book-1?context=READLIST&contextId=readlist-2',
        'selector': '[data-testid="browse-book-root"]',
        'panelSelector': '[data-testid="browse-book-readlists-panel"]',
        'panelKey': 'readlistsPanelFound',
        'panelExpected': True,
        'siblingNavigationSelector': '[data-testid="browse-book-sibling-navigation"]',
        'siblingNavigationExpected': True,
        'sourceFile': 'komga-webui/src/views/BrowseBook.vue',
        'sourceFiles': [
            'komga-webui/src/views/BrowseBook.vue',
            'komga-webui/src/services/komga-readlists.service.ts',
            'komga-webui/src/types/context.ts',
            'komga-webui/src/types/items.ts',
        ],
        'sourceMetadataFragments': [
            'book.seriesTitle',
            'book.metadata.title',
            'book.size',
            "this.$komgaReadLists.getBooks(this.context.id, {unpaged: true} as PageRequest)",
            'this.$komgaReadLists.getBookSiblingNext(this.context.id, bookId)',
            'this.$komgaReadLists.getBookSiblingPrevious(this.context.id, bookId)',
        ],
        'metadataFragments': ['book.cbr', '222 b', 'alice', '2024'],
        'metadataMinimumMatches': 2,
        'ownedRequests': [
            {
                'label': 'readlist-books-unpaged',
                'method': 'GET',
                'urlEndsWith': '/api/v1/readlists/readlist-2/books?unpaged=true',
                'requestPath': '/api/v1/readlists/readlist-2/books?unpaged=true',
                'responseStatuses': [200],
            },
            {
                'label': 'readlist-book-next',
                'method': 'GET',
                'urlEndsWith': '/api/v1/readlists/readlist-2/books/book-1/next',
                'requestPath': '/api/v1/readlists/readlist-2/books/book-1/next',
                'responseStatuses': [200],
            },
            {
                'label': 'readlist-book-previous',
                'method': 'GET',
                'urlEndsWith': '/api/v1/readlists/readlist-2/books/book-1/previous',
                'requestPath': '/api/v1/readlists/readlist-2/books/book-1/previous',
                'responseStatuses': [404],
            },
        ],
        'scenario': {
            'type': 'readlist-sibling-navigation',
            'contextOrigin': 'READLIST',
            'contextId': 'readlist-2',
            'readListName': 'ReadList 2',
            'entryBookId': 'book-1',
            'entryBookPath': '/book/book-1?context=READLIST&contextId=readlist-2',
            'nextBookId': 'book-2',
            'nextBookPath': '/book/book-2?context=READLIST&contextId=readlist-2',
            'seriesNextBookId': 'book-3',
        },
    },
    'browse-oneshot': {
        'route': 'browse-oneshot',
        'path': '/oneshot/series-oneshot',
        'selector': '[data-testid="browse-oneshot-root"]',
        'panelSelector': '[data-testid="browse-oneshot-collections-panel"]',
        'panelKey': 'collectionsPanelFound',
        'panelExpected': True,
        'siblingNavigationSelector': '[data-testid="browse-oneshot-readlists-panel"]',
        'siblingNavigationExpected': True,
        'sourceFile': 'komga-webui/src/views/BrowseOneshot.vue',
        'sourceFiles': [
            'komga-webui/src/views/BrowseOneshot.vue',
            'komga-webui/src/components/CollectionsExpansionPanels.vue',
            'komga-webui/src/components/ReadListsExpansionPanels.vue',
            'komga-webui/src/types/context.ts',
        ],
        'scenarioSourceFiles': [
            'komga-webui/src/views/BrowseOneshot.vue',
            'komga-webui/src/types/context.ts',
        ],
        'sourceMetadataFragments': [
            'book.metadata.title',
            'book.size',
            'this.$komgaSeries.getCollections(seriesId)',
            'this.$komgaBooks.getReadLists(this.book.id)',
        ],
        'metadataFragments': ['oneshot', '150 b', 'download'],
        'metadataMinimumMatches': 2,
        'ownedRequests': [
            {
                'label': 'oneshot-series-detail',
                'method': 'GET',
                'urlEndsWith': '/api/v1/series/series-oneshot',
                'requestPath': '/api/v1/series/series-oneshot',
            },
            {
                'label': 'oneshot-series-collections',
                'method': 'GET',
                'urlEndsWith': '/api/v1/series/series-oneshot/collections',
                'requestPath': '/api/v1/series/series-oneshot/collections',
            },
            {
                'label': 'oneshot-bootstrap-books-list',
                'method': 'POST',
                'urlEndsWith': '/api/v1/books/list',
                'postDataIncludes': ['SeriesId', 'series-oneshot'],
                'requestPath': '/api/v1/books/list',
                'body': '{"condition":{"type":"SeriesId","operator":"is","value":"series-oneshot"}}',
            },
            {
                'label': 'oneshot-book-readlists',
                'method': 'GET',
                'urlEndsWith': '/api/v1/books/book-oneshot/readlists',
                'requestPath': '/api/v1/books/book-oneshot/readlists',
            },
            {
                'label': 'readlist-detail',
                'method': 'GET',
                'urlEndsWith': '/api/v1/readlists/readlist-2',
                'requestPath': '/api/v1/readlists/readlist-2',
                'responseStatuses': [200],
            },
            {
                'label': 'readlist-books-unpaged',
                'method': 'GET',
                'urlEndsWith': '/api/v1/readlists/readlist-2/books?unpaged=true',
                'requestPath': '/api/v1/readlists/readlist-2/books?unpaged=true',
                'responseStatuses': [200],
            },
            {
                'label': 'readlist-book-next',
                'method': 'GET',
                'urlEndsWith': '/api/v1/readlists/readlist-2/books/book-oneshot/next',
                'requestPath': '/api/v1/readlists/readlist-2/books/book-oneshot/next',
                'responseStatuses': [404],
            },
            {
                'label': 'readlist-book-previous',
                'method': 'GET',
                'urlEndsWith': '/api/v1/readlists/readlist-2/books/book-oneshot/previous',
                'requestPath': '/api/v1/readlists/readlist-2/books/book-oneshot/previous',
                'responseStatuses': [404],
            },
        ],
        'observedRequests': [],
        'observedFallbackRequests': [],
        'scenarioSignalExpectations': {
            'readlistContextRetained': True,
            'readlistContextBannerVisible': True,
            'readlistContextNavigationFound': True,
            'returnedToDirectOneshot': True,
        },
        'scenario': {
            'type': 'oneshot-readlist-fallback',
            'seriesId': 'series-oneshot',
            'bookId': 'book-oneshot',
            'readListId': 'readlist-2',
            'readListName': 'ReadList 2',
            'readlistContextPath': '/oneshot/series-oneshot?context=READLIST&contextId=readlist-2',
            'readlistContextNavigationSelector': '[data-testid="browse-oneshot-readlist-context-navigation"]',
        },
    },
}
