#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SeriesSort {
    MetadataTitleSortAsc,
    MetadataTitleSortDesc,
    NameAsc,
    NameDesc,
    CreatedDateAsc,
    CreatedDateDesc,
    LastModifiedDateAsc,
    LastModifiedDateDesc,
    ReleaseDateAsc,
    ReleaseDateDesc,
    BooksCountAsc,
    BooksCountDesc,
    CollectionNumberAsc,
    CollectionNumberDesc,
    ReadDateAsc,
    ReadDateDesc,
    Random,
    RelevanceAsc,
    RelevanceDesc,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BookSort {
    MetadataTitleAsc,
    MetadataTitleDesc,
    CreatedDateAsc,
    CreatedDateDesc,
    LastModifiedDateAsc,
    LastModifiedDateDesc,
    ReadProgressLastModifiedAsc,
    ReadProgressLastModifiedDesc,
    ReadProgressReadDateAsc,
    ReadProgressReadDateDesc,
    ReleaseDateAsc,
    ReleaseDateDesc,
    NumberSortAsc,
    NumberSortDesc,
    SeriesIdAsc,
    Random,
    RelevanceAsc,
    RelevanceDesc,
}
