#[derive(Clone)]
pub(in crate::discovery) struct PersistedSeriesSummary {
    pub(in crate::discovery) id: String,
    pub(in crate::discovery) library_id: String,
    pub(in crate::discovery) name: String,
    pub(in crate::discovery) title: String,
    pub(in crate::discovery) title_sort: String,
    pub(in crate::discovery) labels: Vec<String>,
    pub(in crate::discovery) created: String,
    pub(in crate::discovery) last_modified: String,
    pub(in crate::discovery) file_last_modified: String,
    pub(in crate::discovery) books_count: u64,
    pub(in crate::discovery) books_read_count: u64,
    pub(in crate::discovery) books_unread_count: u64,
    pub(in crate::discovery) books_in_progress_count: u64,
    pub(in crate::discovery) status: String,
    pub(in crate::discovery) summary: String,
    pub(in crate::discovery) reading_direction: String,
    pub(in crate::discovery) publisher: String,
    pub(in crate::discovery) age_rating: Option<u32>,
    pub(in crate::discovery) language: String,
    pub(in crate::discovery) genres: Vec<String>,
    pub(in crate::discovery) tags: Vec<String>,
    pub(in crate::discovery) alternate_titles: Vec<String>,
    pub(in crate::discovery) metadata_created: String,
    pub(in crate::discovery) metadata_last_modified: String,
    pub(in crate::discovery) books_metadata_authors: Vec<String>,
    pub(in crate::discovery) books_metadata_tags: Vec<String>,
    pub(in crate::discovery) books_metadata_release_date: Option<String>,
    pub(in crate::discovery) books_metadata_summary: String,
    pub(in crate::discovery) books_metadata_summary_number: String,
    pub(in crate::discovery) books_metadata_created: String,
    pub(in crate::discovery) books_metadata_last_modified: String,
    pub(in crate::discovery) deleted: bool,
    pub(in crate::discovery) oneshot: bool,
    pub(in crate::discovery) status_lock: bool,
    pub(in crate::discovery) title_lock: bool,
    pub(in crate::discovery) title_sort_lock: bool,
    pub(in crate::discovery) summary_lock: bool,
    pub(in crate::discovery) reading_direction_lock: bool,
    pub(in crate::discovery) publisher_lock: bool,
    pub(in crate::discovery) age_rating_lock: bool,
    pub(in crate::discovery) language_lock: bool,
    pub(in crate::discovery) genres_lock: bool,
    pub(in crate::discovery) tags_lock: bool,
    pub(in crate::discovery) total_book_count_lock: bool,
    pub(in crate::discovery) sharing_labels_lock: bool,
    pub(in crate::discovery) links_lock: bool,
    pub(in crate::discovery) alternate_titles_lock: bool,
    pub(in crate::discovery) links: Vec<PersistedSeriesSummaryLink>,
}

#[derive(Clone)]
pub(in crate::discovery) struct PersistedSeriesSummaryLink {
    pub(in crate::discovery) label: String,
    pub(in crate::discovery) url: String,
}
