pub mod books;
pub mod detail;
mod facets;
pub mod persisted;
mod query;
pub mod series;
mod series_routes;

pub(crate) use books::books_deprecated_get as books_route;
pub(crate) use books::series_books_deprecated as series_books_route;
pub(crate) use detail::series_collections as series_collections_route;
pub(crate) use detail::series_detail as series_detail_route;
pub(crate) use detail::series_metadata_update as series_metadata_update_route;
pub(crate) use facets::age_ratings as age_ratings_route;
pub(crate) use facets::authors_deprecated_get as authors_route;
pub(crate) use facets::authors_names as authors_names_route;
pub(crate) use facets::authors_roles as authors_roles_route;
pub(crate) use facets::authors_v2 as authors_v2_route;
pub(crate) use facets::genres as genres_route;
pub(crate) use facets::languages as languages_route;
pub(crate) use facets::publishers as publishers_route;
pub(crate) use facets::series_release_dates as series_release_dates_route;
pub(crate) use facets::series_tags as series_tags_route;
pub(crate) use facets::sharing_labels as sharing_labels_route;
pub(crate) use facets::tags as tags_route;
pub(crate) use series::series_alphabetical_groups as series_alphabetical_groups_route;
pub(crate) use series::series_deprecated_get as series_route;
pub(crate) use series::series_latest as series_latest_route;
pub(crate) use series::series_new as series_new_route;
pub(crate) use series::series_updated as series_updated_route;
