[package]
name = "komga-epub"
version.workspace = true
edition.workspace = true

[dependencies]
flate2.workspace = true
iepub.workspace = true
quick-xml.workspace = true
regex.workspace = true
serde_json.workspace = true
zip.workspace = true

[dev-dependencies]
image.workspace = true
zip.workspace = true
