[package]
name = "komga-interfaces"
version = "0.1.0"
edition.workspace = true

[features]
allow-missing-webui-dist = []

[dependencies]
axum.workspace = true
axum-extra.workspace = true
base64.workspace = true
bcrypt.workspace = true
flate2.workspace = true
http-body.workspace = true
image.workspace = true
icu.workspace = true
language-tags.workspace = true
komga-domain = { path = "../domain" }
komga-application = { path = "../application" }
komga-kepubify = { path = "../kepubify" }
komga-infrastructure = { path = "../infrastructure" }
lopdf.workspace = true
mime_guess.workspace = true
oauth2.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
regex.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower-http.workspace = true
tracing.workspace = true
tsid.workspace = true
futures-util.workspace = true
async-trait.workspace = true
zip.workspace = true
sqlx.workspace = true
unicode-normalization.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
sqlx.workspace = true

[build-dependencies]
komga-build-support = { path = "../build-support" }
