name: build-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          java-package: 'jdk'
          distribution: 'temurin'

      - name: npm install
        working-directory: komga-webui
        run: npm install
      - name: npm build
        working-directory: komga-webui
        run: |
          npm run build
          mkdir ../komga/src/main/resources/public
          cp -r dist/* ../komga/src/main/resources/public/
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew :komga:prepareThymeLeaf :komga:bootJar :komga-tray:jar
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      - name: ls
        run: |
          version=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          echo "version=v$version" >> $GITHUB_ENV
          ls komga/build
          cp -r komga/build/*
            - name: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: komga-build
          path: komga/build/libs/*.jar
          if-no-files-found: error
