name: build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          java-package: 'jdk'
          distribution: 'temurin'

      - name: npm install
        working-directory: komga-webui
        run: npm install
      - name: npm build
        working-directory: komga-webui
        run: |
          npm run build
          mkdir ../komga/src/main/resources/public
          cp -r dist/* ../komga/src/main/resources/public/
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :komga:prepareThymeLeaf :komga:bootJar
      - name: ls
        run: |
          version=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          echo "version=v$version" >> $GITHUB_ENV
          ls komga/build
          cp -r komga/build/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version }}
          body: ${{ env.version }}
          tag_name: ${{ env.version }}
          append_body: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            komga/build/libs/*.jar

      - name: Set up QEMU (for emulating ARM)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (multi-platform)
        uses: docker/build-push-action@v4
        with:
          context: ./komga
          file: ./komga/docker/Dockerfile.tpl
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dyphire/komga-cn:latest
            dyphire/komga-cn:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/komga-cn:latest
            ghcr.io/${{ github.repository_owner }}/komga-cn:${{ env.version }}

      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v4.0.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: dyphire/komga-cn
          README_FILEPATH: ./README.md
