name: Update DockerHub description

on:
  workflow_dispatch:

jobs:
  update_docker_description:
    name: Update DockerHub description
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v4.0.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: wushuo894/komga-cn
          README_FILEPATH: ./README.md
