name: Tests

on:
  pull_request:
    paths-ignore:
      - 'komga-webui/src/locales/*'
      - 'komga-tray/src/main/resources/org/gotson/komga/*'
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          java-package: 'jdk'
          distribution: 'temurin'

      - name: npm install
        working-directory: komga-webui
        run: npm install
      - name: npm build
        working-directory: komga-webui
        run: |
          npm run build
          mkdir ../komga/src/main/resources/public
          cp -r dist/* ../komga/src/main/resources/public/
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :komga:bootJar
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      - name: ls
        run: |
          ls komga/build
          cp -r komga/build/*
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: komga/build/libs/*.jar
